### ISSUE TITLE
怎么在裁剪之前压缩图片

### ISSUE THREAD

**Issue by 1244752609** [Bilibili/boxing#102]
相机拍出来的照片有点大，每次到裁剪的时候会卡一下，我想在裁剪之前把图片压缩，请问在那个位置处理并压缩？

**Comment by ChenSiLiang** [comment]
裁剪会压 在裁剪之前压也是会卡一下的。

**Comment by 1244752609** [comment]
图片裁剪的时候会卡，有什么好解决的办法？
