### ISSUE TITLE
显示状态的小bug

### ISSUE THREAD

**Issue by chlss** [Bilibili/boxing#103]
在列表外面选中一张图片，然后点击预览，再取消选中，返回时该张图片的选中状态任然为选中！
改下：
PickerPresenter的checkSelectedMedia方法：
if (allMedias == null || allMedias.size() == 0
                || selectedMedias == null || selectedMedias.size() == 0) {
            return;
        }
改为：
        if (allMedias == null || allMedias.size() == 0) {
            return;
        }

**Comment by ChenSiLiang** [comment]
已修复。
