### ISSUE TITLE
多进程的加载

### ISSUE THREAD

**Issue by shaycormac** [Bilibili/boxing#104]
嗨，你好，请问这个框架以后会不会考虑多进程的加载呢，就是我打开贵项目，使用一个私有的进程去加载，现在的版本由于使用BoxingManager.getInstance().setBoxingConfig和getBoxingConfig,导致跨进程出现两个单例，无法传主进程的参数到子进程中，要是改动你们框架，发现很麻烦，所以就是问问你们，谢谢了。

**Comment by ChenSiLiang** [comment]
activity本身支持多进程，使用Boxing.of.start方法启动就行。

**Comment by shaycormac** [comment]
@ChenSiLiang  感谢你的回复，我在项目中涉及到图片选择，默认最多只能选择9张，一种场景是用户选择了3张后，再进去，那么只能让他最多选择6张了，我现在通过BoxConfig的maxCount将参数传过去，发现子进程的maxCount还是默认的9，两个进程中两个单例BoxingManager.造成的吧，也就是说想把参数带过去，发现是失败的，我尝试你说的方法试试，再次感谢你的回复，这个开源框架做的很棒，一直在关注~
