### ISSUE TITLE
三星S4手机拍照OOM

### ISSUE THREAD

**Issue by HotBitmapGG** [Bilibili/boxing#105]
Throwing OutOfMemoryError "Failed to allocate a 38340876 byte allocation with 16777120 free bytes and 23MB until OOM"

**Comment by ChenSiLiang** [comment]
必现？手机拍一张30多m?

**Comment by HotBitmapGG** [comment]
这个问题很麻烦，因为这个手机比较旧，内存太小，后台开点别的应用，在用app的拍照就直接oom了，我了个去
