### ISSUE TITLE
图片多选左右滑动加载有点慢

### ISSUE THREAD

**Issue by gaogq3** [Bilibili/boxing#108]
试了下图片多选点进去查看大图，然后左右滑动大图，发现加载需要大约0.5到1秒的时间。对比了下微信的相册左右滑动，没有延迟。请问有什么优化方法吗？

**Comment by ChenSiLiang** [comment]
降低大图预览的分辨率。

**Comment by Pluckypan** [comment]
@ChenSiLiang  @gaogq3  最近在研究加载大图、动图、缩放的图片浏览器相关的问题，发现如果只是单纯的使用photoview 加载大图（不需要很大 大概4000*3000）的图左右滑动 必然会卡顿（经测试坚果R1勉强能接受 但是仍然能感受到掉帧），解决方案：
1.如果没有查看原始图片的需求  可以加载缩略图（降低分辨率）
2.替换掉photoview 按区域加载大图 可以github搜索 image\photo 之类的关键字 有解决方案

**Comment by ChenSiLiang** [comment]
@Pluckypan 按需替换
