### ISSUE TITLE
多选模式

### ISSUE THREAD

**Issue by Ztiany** [Bilibili/boxing#11]
impl模块中：

1：多选模式时，是否可以支持设置选择的数量,现在写死为9.

```java
         private static final int MAX_SELECTED_COUNT = 9;
```
2：错别字

```xml
    <string name="load_image_fail">肥肠抱歉，加载出错啦</string>
    <string name="crop_error">肥肠抱歉，裁剪出错啦</string>
```

**Comment by ChenSiLiang** [comment]
In fact, it's more recommended to implement lib `boxing` instead of using  lib `boxing-impl`.
There are our rules in `boxing-impl`.
Define your own rules through `boxing`.
By the way, the words are deliberately written.

**Comment by Ztiany** [comment]
Ok, thank you for your answer,
