### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by qzqs** [Bilibili/boxing#115]
导入后出现
F:\new_ned\NeSnd\app\src\main\AndroidManifest.xml:27:9-41 Error:
	Attribute application@label value=(@string/app_name) from AndroidManifest.xml:27:9-41
	is also present at [com.bilibili:boxing-impl:0.8.0] AndroidManifest.xml:28:9-48 value=(@string/boxing_app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:23:5-104:19 to override.
F:\new_ned\NeSnd\app\src\main\AndroidManifest.xml:30:9-40 Error:
	Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:30:9-40
	is also present at [com.bilibili:boxing-impl:0.8.0] AndroidManifest.xml:29:9-47 value=(@style/Boxing.AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:23:5-104:19 to override.
改了很久没有成功，请问作者该怎么解决呢

**Comment by ChenSiLiang** [comment]
更新一下最新版本试试

**Comment by qzqs** [comment]
已经解决，因为作者的版本里面也使用了android:theme和android:label，打包合并就会有冲突，按照提示添加就解决了
