### ISSUE TITLE
更新 1.0.1 版本后 IndexOutOfBoundsExceptionInconsistency 出现的更频繁了

### ISSUE THREAD

**Issue by yueban** [Bilibili/boxing#116]
fabric 监测：

```
Fatal Exception: java.lang.IndexOutOfBoundsExceptionInconsistency detected. Invalid view holder adapter positionViewHolder{a156a67 position=2661 id=-1, oldPos=987, pLpos:987 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{94500c6 VFED.V... ......ID 0,0-720,1072 #7f090192 app:id/media_recycleview}, adapter:com.bilibili.boxing_impl.a.b@7c1d887, layout:android.support.v7.widget.GridLayoutManager@cec83b4, context:com.magic.tribe.android.module.imageselect.MagicBoxingActivity@b6418c5
```

`MagicBoxingActivity` 是继承于 `AbsBoxingActivity` 的界面，修改了 ui 样式

**Comment by ChenSiLiang** [comment]
有自己调用adapter的notifychange方法吗？

**Comment by yueban** [comment]
只有两处和 BoxingViewFragment 完全相同的 `notifyDataSetChanged` 调用，没有额外的调用。
我们从 1.0.0 升级到 1.0.1 是根据 commit changes 来改的，没有调整 Activity， Fragment 中关于 adapter 的调用代码。

**Comment by ChenSiLiang** [comment]
数据变更的时候也都调了notifyItemRangeInserted 和notifyItemRangeRemoved？
如果要调notifyDataSetChanged要保证没有多线程修改和显示adapter的数据

**Comment by yueban** [comment]
恩，这两处的代码和 BoxingActivity 中的完全相同，没有多线程操作

**Comment by ChenSiLiang** [comment]
具体的操作步骤或者机型信息有吗?

**Comment by yueban** [comment]
![image](https://user-images.githubusercontent.com/5647837/36592005-ecc4bc3e-18ce-11e8-8b93-da7a62ac864b.png)

从统计来看，全版本都有这个问题，应该不是特定机型的问题

**Comment by ChenSiLiang** [comment]
fixed.
