### ISSUE TITLE
老实报IndexOutOfBoundsException这个异常

### ISSUE THREAD

**Issue by to686312** [Bilibili/boxing#118]
IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1646feaf position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached not recyclable(1) no parent} android.support.v7.widget.RecyclerView{34edd245 VFED.V.. ......ID 0,0-540,842 #7f0e011c app:id/media_recycleview}, adapter:com.bilibili.boxing_impl.adapter.BoxingMediaAdapter@25b1bd9a, layout:android.support.v7.widget.GridLayoutManager@338ed6cb, context:com.bilibili.boxing_impl.ui.BoxingActivity@4e0fedd  

这个我去查了 是这个框架的问题

**Comment by to686312** [comment]
是1.0.1 这个版本

**Comment by to686312** [comment]
华为 小米 都有

**Comment by to686312** [comment]
要不加个联系方法 我给你录视频给你

**Comment by ChenSiLiang** [comment]
试下依赖最新的master分支，看看还有没有问题

**Comment by to686312** [comment]
好的  我试试哈

**Comment by to686312** [comment]
是1.0.2 这版本的

**Comment by to686312** [comment]
我这边还遇到 一种情况 发现我在用这个框架去 相册选择照片   选完照片 在onactivityresult中也拿到图片   但是在此选择相册去 选择同样的照片  发现 这张照片没有了

**Comment by ChenSiLiang** [comment]
fixed.
