### ISSUE TITLE
缩略图有些无法加载

### ISSUE THREAD

**Issue by zouyuanfeng** [Bilibili/boxing#12]
在加载图片列表中，有些图片无法正常显示，使用Picasso加载图片的缩略图报no such file or directory异常，而使用图片原图加载则正常。手机型号为：zuk z1,小米3c。
[详情图](http://itzyf.qiniudn.com/itzyf_xiaoguotu.jpg)

另
boxing-impl/src/main/res/values/strings.xml：41行有错字
`<string name="crop_error">肥肠（非常）抱歉，裁剪出错啦</string>`

**Comment by ChenSiLiang** [comment]
估计原因是 缩略图存在，但是文件失效了。
这个问题在遇到一些已卸载的APP但是没清空资源时会发生。
可以debug看一下缩略图的路径是否合法。

提示字段是故意写成这样的。

**Comment by zouyuanfeng** [comment]
debug看着是正常的路径，我用手机自带的图库也能正常看到其他图片的
[图库与app对比](http://itzyf.qiniudn.com/itzyf_tu2.jpg)
[报错信息图](http://itzyf.qiniudn.com/itzyf_ex.jpg)

**Comment by ChenSiLiang** [comment]
可以checkout 分支 feature/fix-thumbnail 试试解决问题没？

**Comment by zouyuanfeng** [comment]
问题解决了，确实都能显示了
