### ISSUE TITLE
拍照的图片存储地址无法修改

### ISSUE THREAD

**Issue by liuyong1993** [Bilibili/boxing#120]
无法修改拍照的图片存储地址

**Comment by ChenSiLiang** [comment]
目前只能修改/sdcard/DCIM下子目录的名字

**Comment by Strong-Man** [comment]
needCamera()  点击拍照的这个图片怎么设置好啊?

**Comment by ChenSiLiang** [comment]
@Strong-Man 可以用demo里的ic_boxing_camera_white，或者自己下一个
