### ISSUE TITLE
请问下,设置相册每行显示图片的数量的api有吗?

### ISSUE THREAD

**Issue by Strong-Man** [Bilibili/boxing#121]

**Comment by joimxjtuse** [comment]
看起来没有， 但是这个可以自己扩展下BoxingConfig.java设置个int rowMax， 在BoxingViewFragment.initRecycleView()时改一下layoutmanager，应该不复杂。

**Comment by Strong-Man** [comment]
好的! 谢谢啦

**Comment by ChenSiLiang** [comment]
没有 鼓励自己写UI
