### ISSUE TITLE
多选的时候出现问题

### ISSUE THREAD

**Issue by everyline** [Bilibili/boxing#123]
多选的时候  拍照和 选择图片 依次交替后  拍照之后 图片返回不到我的页面 只会停留到打开的相册

**Comment by everyline** [comment]
![default](https://user-images.githubusercontent.com/8476579/40341482-fef2cef4-5db7-11e8-82fb-9df71e2ab818.png)

**Comment by everyline** [comment]
![default](https://user-images.githubusercontent.com/8476579/40341482-fef2cef4-5db7-11e8-82fb-9df71e2ab818.png)

**Comment by ChenSiLiang** [comment]
异常是什么？
