### ISSUE TITLE
获取图片size返回0

### ISSUE THREAD

**Issue by kgbky** [Bilibili/boxing#125]
选择完图片之后，通过BaseMedia类的getSize() 获取图片大小。返回0

**Comment by Pluckypan** [comment]
如果读取的是系统媒体库的数据 则极有可能存在无法准确获取 媒体信息的情况。
不只是 size,duration 同样也可能存在这样的问题。
应该不是所有手机都存在这个问题

**Comment by ChenSiLiang** [comment]
目前版本是读数据库的数据
