### ISSUE TITLE
图片框架切换为Glide会导致二次选择图片报错

### ISSUE THREAD

**Issue by Xxxxxxyk** [Bilibili/boxing#13]
将图片加载框架改为Glide时,第一次选择图片可以正常显示,然后在进行选择会加载图片失败,报错位置为BoxingGlideLoader的44行,You must not call setTag() on a view Glide is targeting,原因为Item的布局简化代码,需外部嵌套父布局即可正常显示

**Comment by ChenSiLiang** [comment]
demo里的loader不能用在生产环境。
在[Glideissue #370](https://github.com/bumptech/glide/issues/370) 有
多嵌套一层肯定不可以，可以试试调用`ViewTarget.setTagId();`
我没有重现出来这个问题
