### ISSUE TITLE
 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by JakeWoki** [Bilibili/boxing#135]
Inconsistency detected. Invalid view holder adapter positionViewHolder{3ee0c1 position=21 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached not recyclable(1) no parent} android.support.v7.widget.RecyclerView{655a313 VFED.V... .F....ID 0,0-1080,1568 #7f090194 app:id/k_}, adapter:ah.b@dd86950, layout:android.support.v7.widget.GridLayoutManager@91b6749, context:com.bilibili.boxing_impl.ui.BoxingActivity@b1b099a

bugly捕获到的，不是很详细。。。

**Comment by ChenSiLiang** [comment]
最新的代码已修复 不过没更新到gradle

**Comment by JakeWoki** [comment]
https://github.com/Bilibili/boxing/commit/4160e67974a08cea6a2ff9f2d5797aef965bbaf3
这个吗？

**Comment by ChenSiLiang** [comment]
已更新gradle
