### ISSUE TITLE
华为P20手机拍照后不跳转裁剪页面!

### ISSUE THREAD

**Issue by hedongdongv** [Bilibili/boxing#137]

**Comment by hedongdongv** [comment]
问题进一步明确.在外部申请权限后调用就会出现这问题. 但在此库运行时申请权限不会出这种问题.

**Comment by Pluckypan** [comment]
记得华为手机（很久以前）存在一个问题 如果裁剪比例是1:1时 无法调用裁剪  但是如果设置成9999:9998就可以了
