### ISSUE TITLE
华为手机选择多张图片时，点击预览图片崩溃

### ISSUE THREAD

**Issue by lucky-you** [Bilibili/boxing#138]
在最新的1.0.4版本中，选择多张图片的时候，点击预览图片闪退。
![image](https://user-images.githubusercontent.com/22268878/46717558-f6a77680-cc9a-11e8-893a-016943f1aa64.png)

**Comment by ChenSiLiang** [comment]
检查一下 #117

**Comment by lucky-you** [comment]
我查看了我的项目，我的项目中之前并没有引用过PhotoView这个库，引用的其他库中处理除了boxing，其他的也没有引用PhotoView的。

**Comment by ChenSiLiang** [comment]
clean试试

**Comment by lucky-you** [comment]
我查看了你源代码中引用的photoView库，版本比较低了，会不会是这个引起的异常呢？

**Comment by 751496032** [comment]
> 我查看了你源代码中引用的photoView库，版本比较低了，会不会是这个引起的异常呢？

你好，我的也是这个问题，是怎么解决的

**Comment by lucky-you** [comment]
> > 我查看了你源代码中引用的photoView库，版本比较低了，会不会是这个引起的异常呢？
> 
> 你好，我的也是这个问题，是怎么解决的

我没有用他的了
