### ISSUE TITLE
小米5a手机多选 ，点击预览就闪退 

### ISSUE THREAD

**Issue by 751496032** [Bilibili/boxing#141]
![image](https://user-images.githubusercontent.com/13871838/48302610-69756d00-e539-11e8-9bad-60426144b29e.png)

另外我在代码上尝试写PhotoView，并没有PhotoView这个类提示：

![image](https://user-images.githubusercontent.com/13871838/48302638-f5879480-e539-11e8-9e15-d5a8988369c8.png)
这样是不是PhotoView这个库没有引用到？

**Comment by ChenSiLiang** [comment]
不能与PhtotView 共用
