### ISSUE TITLE
选多张图片并预览的时候，把预览界面的右上角对号勾选掉，再次左右滑动会报错

### ISSUE THREAD

**Issue by wushaoge** [Bilibili/boxing#17]
选多张图片并预览的时候，把预览界面的右上角对号勾选掉，再次左右滑动会报错

**Comment by ChenSiLiang** [comment]
有空可以checkout feature/fix-preview看看还有问题嘛

**Comment by wushaoge** [comment]
图片选择和剪裁个人感觉剥离出来，还有选择界面可以提供更多的方法，比如设置按钮颜色之类的，demo中图片右上角多选按钮太小了，不好按   个人愚见 ：）

**Comment by ChenSiLiang** [comment]
裁剪功能是分离出来了的，UI的问题就需要自己自定义了，继承`AbsBoxingViewFragment`再写UI。
