### ISSUE TITLE
Loader in Production ?

### ISSUE THREAD

**Issue by alouanemed** [Bilibili/boxing#19]
Hey, Cool library ! 
So you mentionned [here  ](https://github.com/Bilibili/boxing/blob/master/app/src/main/java/com/bilibili/boxing/impl/BoxingPicassoLoader.java#L57) ,in the Picaasso's loader, that it  can <b>not</b> be used in Production Environment.

So what's the alternative to use this library in production ? Thanks.

**Comment by ChenSiLiang** [comment]
I use Fresco in production instead of Picasso.
Glide and Picasso may not be adapt to some extreme cases leading to load image error.
