### ISSUE TITLE
列表快速滑动时点击上方选择文件夹偶尔会报错

### ISSUE THREAD

**Issue by Leu-Z** [Bilibili/boxing#21]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@206917cb

**Comment by ChenSiLiang** [comment]
Fresco 建议还是使用DraweeView而不是imageview，源码中DraweeView会管理bitmap的生命周期还有其他一些缓存策略。
如果坚持要用fresco，比较好的处理方法是依赖boxing库而不是boxing-impl库，自己实现一套界面。
或者用glide，picasso

具体可以参考这两个issue
https://github.com/facebook/fresco/issues/1550
https://github.com/facebook/fresco/issues/1532

**Comment by hzw1199** [comment]
可以参考如下做法：
https://blog.zongheng.pro/2019/07/11/%e9%80%9a%e8%bf%87fresco%e6%b8%b2%e6%9f%93%e5%9b%be%e7%89%87%e5%88%b0recyclerview%e4%b8%ad%e7%9a%84imageview%e4%b8%ad/
