### ISSUE TITLE
关于图片存放目录的问题

### ISSUE THREAD

**Issue by ppg408331701** [Bilibili/boxing#24]
1.选择自带压缩拍照后的图片是存2份?一份原图在DCIM文件夹,一份压缩后的在APP自己的catch目录?
2.如果不想放在DCIM的话可以选择不放吗?如何操作
3.想压缩得更小一些,即使模糊一点也行,在哪里调整压缩率

**Comment by ChenSiLiang** [comment]
暂时只能放在DCIM里面某个文件夹
压缩可以指定最大压缩大小，通过ImageMedia.compress方法可以指定这个大小
