### ISSUE TITLE
主题颜色的问题

### ISSUE THREAD

**Issue by xushaun** [Bilibili/boxing#25]
关于主题颜色的问题，我的colorPrimary被Boxing的colorPrimary覆盖掉，Title显示的一直是黑色，开始我怀疑是主题的问题，在Application中使用了 tools:replace="android:theme"，但是效果还是黑色，请问如何才能不被Boxing的颜色 覆盖掉

**Comment by ChenSiLiang** [comment]
现在资源文件都加了前缀，应该不会冲突了，你再试下

**Comment by xushaun** [comment]
因为我用的依赖不是源代码，是通过gradle，所以如果你不发布，我测试不了

**Comment by xushaun** [comment]
这样应该不会颜色冲突了，请问你什么时候更新到jcenter

**Comment by ChenSiLiang** [comment]
下周会更新

**Comment by xushaun** [comment]
亲，请问你 jcenter 更新了吗

**Comment by ChenSiLiang** [comment]
已更新
