### ISSUE TITLE
impl的style建议

### ISSUE THREAD

**Issue by phoenixsky** [Bilibili/boxing#29]
1. 建议将AppTheme换为Theme.AppCompat.Light.NoActionBar. DarkActionBar会在toolbar的title和menu处加入半透明的背景.
2. 为什么impl的drawable文件夹要加入v4,这样我想在我的项目中重写某些资源还要再建一堆v4的drawable文件夹
3. 建议将图片选中的那个checkbox的资源抽取出来,可以定制.

**Comment by ChenSiLiang** [comment]
哪个文件夹有加v4？
通过module的引入方式也可以自己进行替换

**Comment by phoenixsky** [comment]
不好意思,看错了,v4是引入jcenter项目后自己添加的.
