### ISSUE TITLE
初步使用反馈

### ISSUE THREAD

**Issue by YancyYe** [Bilibili/boxing#31]
1.多选图片的时候（最大9张），缩略图页面  选择了4张后，第五张点进去看大图，右下角显示 4/4，选中了第五张之后  变成正常的 5/9。

2.拍摄照片、裁剪的图片，存放的文件夹可以自己选择嘛？ 现在存放的文件夹是固定的 boxing，在项目中不易统一管理。

3.相册页面滑动时：CloseableReference: Finalized without closing: 187a0660 28262719 (type = CloseableStaticBitmap)这个警告会不停的出现。  

4.多选时，缩略图右上角的选中按钮 点击范围太小，不容易点击。

项目中有很多借鉴的东西，反馈建议只是想让此开源项目更好的让新手开发者使用。期待作者的回复。

**Comment by ChenSiLiang** [comment]
1.应该是个bug，我修下
2.现在是默认存放在DCIM目录下，可以调用CameraPickerHelper.startCameraIntent()的subFolder来指定子目录，但是DCIM目录目前不能更改
3.Fresco如果不适用它自己的Drawee控件会有bitmap的生命周期问题，这个可以看一下Fresco里面的issue，或者看一下这个 #21
4. boxing-ui库是基于boxing库写的界面，跟哔哩哔哩客户端UI大致相同，虽然重新写界面蛮麻烦的，但更建议去自己实现一套UI，而不是直接使用boxing-ui库（如果要用Fresco肯定要自定义UI）。

感谢反馈！
