### ISSUE TITLE
为什么我把IBoxingMediaLoader loader = new BoxingFrescoLoader(this);demo中的这个换成BoxingGlideLoader()就加载不出图呢？

### ISSUE THREAD

**Issue by 52932** [Bilibili/boxing#35]
为什么我把IBoxingMediaLoader loader = new BoxingFrescoLoader(this);demo中的这个换成BoxingGlideLoader()就加载不出图呢？

**Comment by 52932** [comment]
手机是小米5S+

**Comment by ChenSiLiang** [comment]
是代码里替换还是demo里换的？

**Comment by 52932** [comment]
我是根据demo的代码 自己写了一个  然后换成Glide的 就加载不出来图片

**Comment by 52932** [comment]
我的有想是52932@163.com  这样发消息太费劲了，

**Comment by ChenSiLiang** [comment]
有加file://前缀么？debug看一下图片路径对不对

**Comment by maxyqy** [comment]
用Demo的话， FirstActivity的onBindViewHolder里面需要去掉mediaViewHolder.itemView.setTag(position);这一行，用Glide不能给它的ImageView设置Tag
