### ISSUE TITLE
横屏状态拍照方向不对

### ISSUE THREAD

**Issue by idongz** [Bilibili/boxing#40]
当我在横屏状态调用拍照功能的时候，拍照界面是竖屏的，导致拍出来的照片方向不对，有没有办法能解决呢?

**Comment by ChenSiLiang** [comment]
你调用的是系统相机？拍完照之后会自动旋转的啊 有没有具体的机型和拍照结果

**Comment by idongz** [comment]
你好，是调用的你们的BoxingActivity，我看了下源码，你们写的是固定竖屏（android:screenOrientation="portrait"）

**Comment by ChenSiLiang** [comment]
相机是通过intent启动的，跟BoxingActivity的方向无关。
