### ISSUE TITLE
拍照后完成响应时间较长

### ISSUE THREAD

**Issue by fzroad** [Bilibili/boxing#41]
公司测试组反馈在oppo A53m手机上拍照完成时响应较慢，经过查看源码定位到
CameraPickerHelper.java文件230-241行：
原代码如下：
int degree = BoxingExifHelper.getRotateDegree(file.getAbsolutePath());
            Matrix matrix = new Matrix();
            if (degree != 0) {
                matrix.postRotate(degree);
            }
            BitmapFactory.Options options = new BitmapFactory.Options();
            options.inJustDecodeBounds = false;
            bitmap = BitmapFactory.decodeFile(file.getAbsolutePath(), options);
            outBitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, false);
            outputStream = new FileOutputStream(file);
            outBitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream);
            outputStream.flush();
建议修改为：
 int degree = BoxingExifHelper.getRotateDegree(file.getAbsolutePath());
            Matrix matrix = new Matrix();
            if (degree != 0) {
                matrix.postRotate(degree);
                BitmapFactory.Options options = new BitmapFactory.Options();
                options.inJustDecodeBounds = false;
                bitmap = BitmapFactory.decodeFile(file.getAbsolutePath(), options);
                outBitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, false);
                outputStream = new FileOutputStream(file);
                outBitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream);
                outputStream.flush();
            }
以避免在不需要旋转的时候浪费资源

**Comment by ChenSiLiang** [comment]
这个是写文件操作。
如果像你这样修改，那不需要旋转的时候就不写文件了啊。

**Comment by hxzpp** [comment]
不需要旋转的时候还需要写文件吗，默认拍照完成的时候已经写文件了啊

**Comment by ChenSiLiang** [comment]
有道理，我改下，感谢反馈。

**Comment by hxzpp** [comment]
这里还有个细节要改一下哦，就是在三星s5和魅族2都会oom，我看下主要是图片太大了，应该旋转的时候先压缩下哦，我改了下，效果不错，可以加个好友聊聊，这个项目开源非常的不错哦 373486276

**Comment by hxzpp** [comment]
try {
            int degree = BoxingExifHelper.getRotateDegree(file.getAbsolutePath());
            Matrix matrix = new Matrix();
            if (degree != 0) {
                matrix.postRotate(degree);
                bitmap = ImageCompressor.compressSize(file.getAbsolutePath());
                outBitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, false);
                outputStream = new FileOutputStream(file);
                outBitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream);
                outputStream.flush();
            }
            return true; 我是这么处理的，适配了不少机型，都不错

**Comment by ChenSiLiang** [comment]
拍出来的图片会有多大？

**Comment by hxzpp** [comment]
在三星s5上，我算了下图片加载到内存的时候将近50M，直接爆了

**Comment by ChenSiLiang** [comment]
好 那具体拍出来的图片多大 5M？
 应该对大图采取压缩策略比较合适 因为想存下来的图尽量清晰

**Comment by hxzpp** [comment]
差不多吧，拍照图片一般在4-5M左右，加载到内存大概在40-50M左右，所以容易爆炸，ImageCompressor中的compressDisplay方法压缩应该能达到预期的效果。

**Comment by hxzpp** [comment]
我本来想把画质options.inPreferredConfig = Bitmap.Config.RGB_565;也压缩下，想想怕质量受到影响就暂时不做，先按compressDisplay做，然后测试N个机型，看看反馈的情况在定。。。你有什么好建议记得发我下。
