### ISSUE TITLE
 android.content.res.Resources$NotFoundException: Resource ID #0x1

### ISSUE THREAD

**Issue by xiang473535976** [Bilibili/boxing#45]
BoxingConfig singleImgConfig = new BoxingConfig(BoxingConfig.Mode.SINGLE_IMG);
            singleImgConfig.needCamera(1);
请看看哈

**Comment by yfrflash** [comment]
needCamera()需要资源id，写1肯定不行啊

**Comment by ChenSiLiang** [comment]
调用needCamera的时候需要传入camera的照片。
