### ISSUE TITLE
加了7.0的适配后  启动app就出现了这个 

### ISSUE THREAD

**Issue by xiang473535976** [Bilibili/boxing#48]
Unable to get provider android.support.v4.content.FileProvider: java.lang.SecurityException: Provider must grant uri permissions

**Comment by ChenSiLiang** [comment]
是否参考demo的manifest的写法？有没有授予权限？

**Comment by xiang473535976** [comment]
就是参考demo修改的   请问需要额外加啥权限

**Comment by xiang473535976** [comment]
我看了  就读写内存和 相机 这两个权限我都加了的哈

**Comment by ChenSiLiang** [comment]
有没有加`android:grantUriPermissions="true"`或者你方便吧manifest的代码贴出来看一看？
