### ISSUE TITLE
关闭activity时崩溃

### ISSUE THREAD

**Issue by qienanxiang** [Bilibili/boxing#52]
**com.qienanxiang.tip/com.qienanxiang.tip.activity.EditF3SecondActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-12 08:31:41.719 1617-1915/? E/InputDispatcher: channel 'f1dc6c1 com.qienanxiang.tip/com.qienanxiang.tip.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!**

**Comment by qienanxiang** [comment]
建议更新下Gradle，demo中的库明显高于0.7.0，使用demo中的代码应用Gradle会出问题。

**Comment by ChenSiLiang** [comment]
代码的确比gradle版本要高，两周会更新一次。
