### ISSUE TITLE
为什么多选拍完照就直接返回选择的照片了？

### ISSUE THREAD

**Issue by yuwenyishan** [Bilibili/boxing#58]
多选的情况下点拍照，拍完然后就直接返回选择的照片了！而不是回到选择照片模式！

**Comment by ChenSiLiang** [comment]
这个是产品角度的问题而不是技术角度的问题。可以通过修改源码或者实现lib库写界面实现需求。

**Comment by yuwenyishan** [comment]
好吧！既然设计如此就ok了！
