### ISSUE TITLE
关于返回值

### ISSUE THREAD

**Issue by weinierfei** [Bilibili/boxing#59]
使用的时候有个小疑问,我需要定义自己的实体,ImageMedia或者BaseMedia里的字段不能满足我的需求,不过我看源码中返回的就是List<BaseMedia>,这个应该怎么修改?谢谢

**Comment by ChenSiLiang** [comment]
继承ImageMedia或者BaseMedia，如果你需要从数据库里读更多字段只能修改源码，如果是其他属性的可以选择组合方法把ImageMedia作为一个属性。

**Comment by weinierfei** [comment]
我的实体Entity继承了ImageMedia或者BaseMedia,传给withIntent,选完图片以后,在回调中返回Boxing.getResult(data);  这个值得类型是ArrayList<ImageMedia>;并不是我自己的ArrayList<Entity>,不知道这个咋整?求指导

**Comment by ChenSiLiang** [comment]
噢 这样不行的。因为在查数据库的时候实体类就已经构造好了，跟你外面传什么进去无关。只能改源码了。
你想加什么字段呢？

**Comment by weinierfei** [comment]
项目中原本图片相关实体里头有上传状态之类的标记字段,改造的时候,遇到了问题

**Comment by ChenSiLiang** [comment]
这个字段可以不加在imagemedia里，你可以用组合的方法，把两个东西放到一个新类里面。实在不行的话只能改源码了。

**Comment by weinierfei** [comment]
修改源码的话,就是往imagemedia中添加字段吗?

**Comment by ChenSiLiang** [comment]
可以 但是因为图片选择的过程并没有对你添加的字段进行修改，所以我觉得没什么必要。

**Comment by weinierfei** [comment]
那就是我用组合的方法,将imagemedia作为一个属性,那我给withIntent传值的时候,应该传我新建的类还是imagemedia?

**Comment by ChenSiLiang** [comment]
withIntent方法的imagemedia参数是当你有已选图片的情况下才传的。
你直接传imagemedia就行了。

**Comment by weinierfei** [comment]
好的 ,谢谢
