### ISSUE TITLE
裁剪后，没有回调 onActivityResult

### ISSUE THREAD

**Issue by ittianyu** [Bilibili/boxing#6]
demo上裁剪正常，然后继承到自己的app上就裁剪点击确定后，停留在选择图片界面。
试着把demo里面的 FirstActivity 整个复制过来，发现一样的停留在选择图片界面，一进入 Activity 就初始化了。
```
BoxingMediaLoader.getInstance().init(new BoxingGlideLoader()); // IBoxingMediaLoader
BoxingCrop.getInstance().init(new BoxingUcrop());  // a class implements IBoxingCrop
```
找了好久找不到原因，对比了很久，并没有发现哪里缺了设置，还请指教

**Comment by ittianyu** [comment]
视频选择器中如果加上 needCamera，会报数组越界异常

**Comment by ChenSiLiang** [comment]
视频选择器暂时不支持拍摄录像，所以不能设needCamera。

裁剪的问题，需要更多细节，比如在onActivityResult里面有没有调用super方法？

**Comment by ittianyu** [comment]
调用了

**Comment by ittianyu** [comment]
这是我的demo，裁剪的部分注释掉了 https://github.com/ittianyu/CloudinaryDemo

**Comment by ChenSiLiang** [comment]
裁剪的目录没有正确生成，我做了下保护。

**Comment by ChenSiLiang** [comment]
fix in v0.2.0
