### ISSUE TITLE
默认相册图片数量显示不准确，图片尺寸过滤

### ISSUE THREAD

**Issue by xiyangyuge** [Bilibili/boxing#62]
**0.75版本发现的问题**
1.  默认 `needGif = false` 的时候， `AlbumTask.buildAlbumCover()` 方法没有根据 `needGif` 属性过滤，导致相册列表中如果包含gif图会与图片列表中的数量不匹配
2. 默认相册显示的图片数量 与 所有相册图片数量总和不匹配（`needGif` 等于 true 或 false 的时候都会出现这个问题）

**新增图片尺寸过滤功能**
项目中有个模块上传图片要求宽高或者图片大小大于某个值，现版本中只对 gif 做了过滤。

**现解决方案**
在`AlbumTask.buildAlbumCover()` 中新增了 needGif 过滤支持，移除了 `AlbumTask.buildDefaultAlbum()` 在 `getAlbumList()` 中根据所有相册的图片数计算 `mDefaultAlbum.mCount` 

图片尺寸过滤功能，我在 BoxingConfig 中新增了一个 MediaFilter 属性， 在 `AlbumTask，ImageTask `类的 CursorQuery 方法中 selection 参数追加了 MediaFilter 条件。

 #63

**Comment by ChenSiLiang** [comment]
能不能把新增功能和修复问题的提交分开，这样方便review代码。

**Comment by xiyangyuge** [comment]
OK, 我整理一下
