### ISSUE TITLE
boxing-impl 导入后运行会出现uk.co.senab.photoview 与其他库冲突

### ISSUE THREAD

**Issue by YHRookie** [Bilibili/boxing#64]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: uk/co/senab/photoview/BuildConfig.class

**Comment by ChenSiLiang** [comment]
impl库里面也有photoview，可以通过两种方法解决冲突
1.用impl库里的photoview
2.基于base库写ui
