### ISSUE TITLE
合并冲突，能否去掉 boxing-impl manifest  中的 android:label="@string/boxing_app_name"

### ISSUE THREAD

**Issue by ittianyu** [Bilibili/boxing#70]
作为安卓库来说，android:label android:allowBackup  android:supportsRtl 等不是必须的，留着可能会和主模块起冲突。
    <application
        android:allowBackup="true"
        android:label="@string/boxing_app_name"
        android:supportsRtl="true"
        android:theme="@style/Boxing.AppTheme">

能否考虑去掉这些属性。

**Comment by ChenSiLiang** [comment]
去掉了allowBackup和supportRtl，label冲突的话参考 #50

**Comment by ittianyu** [comment]
我发现你引用了 R.string.boxing_app_name，但是这和 application 里的 label属性理论上没关系，事实上我试着删掉了跑起来也没问题。如果不能删掉，能否改成默认的 app_name。
另外，android:theme 也是可以去掉的，因为你在 activity 中已经加上了 theme。
```
<application
        android:theme="@style/Boxing.AppTheme">
```

你说的解决方案我用了，编译能通过，但 gradle 同步会失败，让人头疼。
