### ISSUE TITLE
压缩图片的方法中MaxSize似乎不起作用

### ISSUE THREAD

**Issue by ppg408331701** [Bilibili/boxing#74]
```
public boolean compress(ImageCompressor imageCompressor, int maxSize) {
        return CompressTask.compress(imageCompressor, this, (long)maxSize);
    }
```
有几个疑问:
1.int maxSize第二个参数要求传int型,但是int型最大只能到65535,而且后面的方法还要转成long型,何不一开始就让传long型呢?
2.
```
  if (imageMedia.compress(new ImageCompressor(mActivity),65534)) {
                    imageMedia.removeExif();
                    imageMedias.add(imageMedia);
                }
```
//不管传1000还是2000或者5000,最后在imageMedia通过 getPath() LogUtils.e("size=="+FileUtils.getFileSize(s.getPath()));打印出来大小都是和不传参数一样

希望能压缩到每张图片250KB左右,这个maxsize应该填多少比较好

**Comment by ChenSiLiang** [comment]
1.我改一下
2.这个maxsize暂时未能限制压缩大小，只是压缩的最小大小。我过会把这个功能加上。取压缩后的路径是`ImageMedia.getCompressPath()`.
