### ISSUE TITLE
BottomSheetFragment和BottomSheetActivity图片选中状态不同步的bug

### ISSUE THREAD

**Issue by allenxuan** [Bilibili/boxing#77]
重现步骤如下：
1. 在图片Preview的界面中选择两张图
![screenshot_1498402582](https://user-images.githubusercontent.com/11569630/27517147-e48922e2-59f9-11e7-907c-832b0f57fa1d.png)
![screenshot_1498402587](https://user-images.githubusercontent.com/11569630/27517148-e655323c-59f9-11e7-8461-140dd5c18c01.png)
2. 点击图片Preview界面右下角的OK按钮，选中的图片被展示出来
![screenshot_1498402602](https://user-images.githubusercontent.com/11569630/27517157-1b83c518-59fa-11e7-98e8-8884c1eb71c0.png)
3. 再次呼出BottomSheetFragment或者BottomSheetActivity，之前选中的两张图对应的缩略图右上角的勾没有了
![screenshot_1498402609](https://user-images.githubusercontent.com/11569630/27517160-3d68872c-59fa-11e7-8d30-3abb38961733.png)

**Comment by ChenSiLiang** [comment]
`BoxingBottomSheetActivity`只支持单选，注释里有写，这只是为自定义界面做的简单示例。
