### ISSUE TITLE
demo中使用BoxingGlideLoader()，第二次选多张图在RecyclerView中显示有问题

### ISSUE THREAD

**Issue by allenxuan** [Bilibili/boxing#78]
（BoxingFrescoLoader和BoxingPicassoLoader没有这个问题）

重现步骤如下：
1. 选5张图点击确定，RecycleView显示没有问题
![screenshot_1498406737](https://user-images.githubusercontent.com/11569630/27517749-075ff962-5a04-11e7-8fe7-42e934ae4434.png)
![screenshot_1498406744](https://user-images.githubusercontent.com/11569630/27517751-079af184-5a04-11e7-99e6-d69b8eaaea47.png)

2. 第二次选2张图，RecyclerView什么也不显示
![screenshot_1498406781](https://user-images.githubusercontent.com/11569630/27517752-0a3da062-5a04-11e7-9330-4cac0e340180.png)
![screenshot_1498406787](https://user-images.githubusercontent.com/11569630/27517753-0b665088-5a04-11e7-8c2d-16cd4dc00d53.png)

**Comment by allenxuan** [comment]
我看到BoxingGlideLoader.java里面的注释提到了Glide的一个issue : // https://github.com/bumptech/glide/issues/1531

在使用Glide时，ImageView.setTag()有时候是不能用滴，所以我把FirstActivity.java中的 mediaViewHolder.itemView.setTag(position);注释掉就OK了

**Comment by ChenSiLiang** [comment]
嗯 这个tag是给Fresco做的加载兼容，这个loader要根据项目实际情况做修改。

**Comment by allenxuan** [comment]
OK，多谢回复
