### ISSUE TITLE
使用PicassoLoader无法加载本地视频的缩略图

### ISSUE THREAD

**Issue by juhuacha18** [Bilibili/boxing#79]
**使用PicassoLoader无法加载本地视频的缩略图的问题**
bilibili 乾杯 - ( ゜- ゜)つロ！！！
感谢作者 写得非常好的一个项目 ～
但是我在使用的时候遇到了一个问题...
因为我们项目使用的是Picasso，并不像Glide那样自带支持视频解码的功能所以进入到Demo中的视频单选界面的时候会出现无法加载缩略图的现象。
如图所示:
<img width="413" alt="59717c1e-8a31-4964-950f-83107a727e65" src="https://user-images.githubusercontent.com/15060771/27530151-fb531330-5a89-11e7-8c8b-000a72cc84dd.png">

Log 输出的错误信息如下：
<img width="1153" alt="7a6870bb-6fd9-4eed-9b2d-d4298e6d9ae0" src="https://user-images.githubusercontent.com/15060771/27530406-1aad4574-5a8b-11e7-9461-2a6518a09c11.png">
<img width="483" alt="b401a491-4aaa-4444-a878-35e46003f030" src="https://user-images.githubusercontent.com/15060771/27530440-448ed858-5a8b-11e7-8a49-ad8a940dfe6f.png">

我观察了一下代码发现VideoMedia没有一个类似于thumb的字段，然后我尝试在VideoTask中加入获取视频缩略图的代码:

```java
Cursor thumbCursor = cr.query(
                            MediaStore.Video.Thumbnails.EXTERNAL_CONTENT_URI,
                            new String [] {MediaStore.Video.Thumbnails.DATA,
                            }, MediaStore.Video.Thumbnails.VIDEO_ID
                                    + "=" + id, null, null);
                    if (thumbCursor.moveToNext()) {
                        String thumb = thumbCursor.getString(thumbCursor
                                .getColumnIndex(MediaStore.Video.Thumbnails.DATA));
                        Log.d("thumb",thumb);
                    }
```
但是并没有返回给我所有的视频缩略图路径，手机里面一共有11个视频但是只返回了我4个缩略图的url。
<img width="483" alt="b401a491-4aaa-4444-a878-35e46003f030" src="https://user-images.githubusercontent.com/15060771/27530454-54b37cd4-5a8b-11e7-914c-bdf566a141ae.png">

我查询了以下资料发现可以使用ThumbUtils这个类自己创建缩略图，但是在我的测试机上明显感觉加载的速度比较慢
想咨询一下作者有没有什么比较高效的方式能获取到本地手机视频缩略图的方法 谢谢

**Comment by ChenSiLiang** [comment]
ThumbUtils的确可以创建缩略图，但是性能比较差；本地缩略图系统不一定都有比较麻烦。
如果一定要用Picasso，只能说有缩略图的用缩略图，没缩略图的先生成，然后存起来，以后加载就很快。

**Comment by juhuacha18** [comment]
项目之前一直使用的是Picasso，我自己先解决试试吧
谢谢～
