### ISSUE TITLE
索尼Z5出现后置摄像头拍照后无法返回activity的情况

### ISSUE THREAD

**Issue by ppg408331701** [Bilibili/boxing#81]
使用的是实现版本0.8.0
系统的7.0    
限制选择2张照片,其他手机如小米6可以拍照后返回正常返回调起的Activity,但是Z5后置摄像头拍照后返回的是boxing的图片选择页面,然后后置摄像头拍出来的照片也没有显示在图片选择的页面中.
另外,前置摄像头正常
```
 BoxingConfig singleImgConfig = new BoxingConfig(BoxingConfig.Mode.MULTI_IMG);
        singleImgConfig.needCamera(R.mipmap.icon_take_photo).needGif().withMaxCount(max);
        Boxing.of(singleImgConfig).withIntent(mActivity, BoxingActivity.class).start(this, TAKEPHOTO_CODE);

**Comment by ChenSiLiang** [comment]
报错信息有没有？可不可以试一下限制照片大小？

**Comment by ppg408331701** [comment]
是的,当我选择2300W像素的模式拍照的时候,就返回不了activity,当选择800W像素的模式的时候就能返回

但是我总不能限制用户选择拍照的像素模式吧,有没有什么解决办法

**Comment by ChenSiLiang** [comment]
看一下2300w像素拍出来的照片多大，估计是压缩后还是太大。

**Comment by ppg408331701** [comment]
5MB 左右
尺寸是5520*4140

**Comment by ChenSiLiang** [comment]
我用最新的索尼机子拍出来的。
7.51Mb， 3700x5000左右是可以的。

**Comment by ppg408331701** [comment]
我测试过了,如果拍照的时候
选择20MP(16:9),可以正常返回
选择23MP(4:3),返回失败

16:9是3366 X 5984的
目前总结出来就是4:3拍照时返回异常
