### ISSUE TITLE
多图预览设置start_pos不起作用

### ISSUE THREAD

**Issue by Lyoona** [Bilibili/boxing#88]
Boxing.get().withIntent(activity,BoxingViewActivity::class.java,media,position).start(activity,BoxingConfig.ViewMode.PREVIEW)

我在使用九宫格显示图片的时候，传入了当前点击的图片的position和数组media，预览页面的坐标是正确的，但是图却是加载的第一张

**Comment by ChenSiLiang** [comment]
kotlin没有详细地测过 欢迎merge.

**Comment by wang0168** [comment]
@Lyoona 
BoxingViewActivity 这个类的startLoading() 方法 把数据集绑定提到前面去就可以了
@Override
    public void startLoading() {
      mAdapter.setMedias(mImages);//数据集绑定放在前面  setCurrentItem才生效
        if (!mNeedLoading) {
            mCurrentImageItem = (ImageMedia) mSelectedImages.get(mStartPos);
            if (mStartPos > 0 && mStartPos < mSelectedImages.size()) {
                mGallery.setCurrentItem(mStartPos, false);
            }
            mToolbar.setTitle(getString(R.string.boxing_image_preview_title_fmt, String.valueOf(mStartPos + 1)
                    , String.valueOf(mSelectedImages.size())));
            mProgressBar.setVisibility(View.GONE);
            mGallery.setVisibility(View.VISIBLE);
        
        } else {
            loadMedia(mAlbumId, mStartPos, mCurrentPage);
          
        }
    }

**Comment by ChenSiLiang** [comment]
你是点预览按钮还是直接点的图片进大图？

**Comment by Lyoona** [comment]
抱歉，前段时间有其它项目，于是乎忘记回复了，wang0168这位朋友给的方案是正确的，希望予以更正，主要出现问题是在选择多图得到回调，显示在自定义的例如九宫格控件中时，点击预览出现这个bug
