### ISSUE TITLE
单独使用大图预览的功能时传入的下标不起作用

### ISSUE THREAD

**Issue by wang0168** [Bilibili/boxing#89]
调用代码：
 Boxing.get().withIntent(this, BoxingViewActivity.class, medias, index, AlbumEntity.DEFAULT_NAME)
                        .start(this, BoxingConfig.ViewMode.PREVIEW);

我修改了 BoxingViewActivity 一行代码顺序
 @Override
    public void startLoading() {
        if (!mNeedLoading) {
            mAdapter.setMedias(mImages);  //绑定数据放在 设置当前显示的前面
            mCurrentImageItem = (ImageMedia) mSelectedImages.get(mStartPos);
            if (mStartPos > 0 && mStartPos < mSelectedImages.size()) {
                mGallery.setCurrentItem(mStartPos, false);
            }
            mToolbar.setTitle(getString(R.string.boxing_image_preview_title_fmt, String.valueOf(mStartPos + 1)
                    , String.valueOf(mSelectedImages.size())));
            mProgressBar.setVisibility(View.GONE);
            mGallery.setVisibility(View.VISIBLE);

        } else {
            loadMedia(mAlbumId, mStartPos, mCurrentPage);
            mAdapter.setMedias(mImages);
        }
    }

**Comment by qianzui** [comment]
该方法有效
