### ISSUE TITLE
FileProvider冲突

### ISSUE THREAD

**Issue by wning8258** [Bilibili/boxing#91]
我的项目里引入了融云，它里面也有FileProvider
```
<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="您的应用包名.FileProvider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/rc_file_path" />
</provider>
```
现在编译的时候，会报错
Error:Execution failed for task ':Main:branches:QiQi_ver_aggregation:processOriDebugManifest'.

Manifest merger failed with multiple errors, see logs
我看咱们的android:authorities="${applicationId}.file.provider"，融云的是android:authorities="您的应用包名.FileProvider"，我不知道该怎么合并？

**Comment by Xuzhiwei** [comment]
在android:authorities中用分号进行分割一起写进去就可以了

**Comment by ChenSiLiang** [comment]
也可以自己写一个fileprovider的xml，然后把需要的内容都添加进去。

**Comment by parcool** [comment]
@Xuzhiwei 分号分割不对啊，直接启动报错
