### ISSUE TITLE
能不能加入直接打开相机功能！

### ISSUE THREAD

**Issue by kamaelyoung** [Bilibili/boxing#92]
能不能加入直接打开相机功能！

**Comment by ChenSiLiang** [comment]
?

**Comment by kamaelyoung** [comment]
就是可以直接通过按钮调起相机功能 拍完照片在boxing 中处理成和选了图片一样的数据格式返回。不知道说的你能看懂吗。。。

**Comment by ChenSiLiang** [comment]
继承Abs类 自己写ui层然后调用CameraPicker 不提供现成UI实现。
