### ISSUE TITLE
引用rotatephotoview:1.0.5  中的PhotoView控件闪退

### ISSUE THREAD

**Issue by xiao80206040** [Bilibili/boxing#93]
compile('com.chensl.rotatephotoview:rotatephotoview:1.0.5') {
 exclude group: 'com.android.support', module: 'appcompat'}

这个框架在缩小放大 多次后会闪退
建议更换 显示缩放的View控件
如：https://github.com/bm-x/PhotoView
等等

**Comment by ChenSiLiang** [comment]
报错信息是什么？
